version: build.{build}

os: Visual Studio 2013

clone_folder: c:\!BuildOSVR\VRTestApp

platform:
 - Win32
# - x64

configuration:
# - Debug
 - Release

#matrix:
# allow_failured:
#  - platform: x64
#    configuration: Debug

install:
 - cmake --version
 - git submodule update --init --recursive -q

before_build:
 - echo "Starting build..."

build:
  project: VRTestApp.sln
  verbosity: detailed

after_build:
 - cmd: mkdir vrtestapp-$(appveyor_build_version)-$(platform)
 - cmd: copy ./Working/SDL2.dll ./vrtestapp-$(appveyor_build_version)-$(platform)/
 - cmd: copy ./Working/openvr_api.dll ./vrtestapp-$(appveyor_build_version)-$(platform)/
 - cmd: copy ./Working/Data ./vrtestapp-$(appveyor_build_version)-$(platform)/
 - cmd: copy ./$(configuration)/VRTestApp.exe ./vrtestapp-$(appveyor_build_version)-$(platform)/

artifacts:
 - path: vrtestapp-$(appveyor_build_version)-$(platform)/*.*
 - path: vrtestapp-$(appveyor_build_version)-$(platform)/Data/*.*
 - path: vrtestapp-$(appveyor_build_version)-$(platform)/Data/Shaders/*.*
 - path: vrtestapp-$(appveyor_build_version)-$(platform)/Data/Textures/*.*

#deploy:
#- provider: GitHub
#  tag: vrtestapp-$(appveyor_build_version)-$(platform)
#  release: vrtestapp-$(appveyor_build_version)-$(platform)
#  description: VR Test App release
#  auth_token:
#    secure: a1D+fCbSKHqq30FF/sF1hGvs+WHLMrZ2JFKkYS4SdjOOdyve83el5ejZrv5cSYDh
#  draft: true
#  prerelease: false
