version: build.{build}

os: Visual Studio 2013

clone_folder: c:\!BuildOSVR\VRTestApp

platform:
 - Win32
# - x64

configuration:
# - Debug
 - Release

#matrix:
# allow_failured:
#  - platform: x64
#    configuration: Debug

install:
 - cmake --version
 - git submodule update --init --recursive -q

before_build:
 - echo "Starting build..."

build:
  project: VRTestApp.sln
  verbosity: detailed

after_build:
 - cmd: mkdir deploy
 - cmd: copy .\Working\SDL2.dll .\deploy\
 - cmd: copy .\Working\openvr_api.dll .\deploy\
 - cmd: copy .\Working\Data .\deploy\
 - cmd: copy .\$(configuration)\VRTestApp.exe .\deploy\

artifacts:
 - path: deploy\*.*
 - path: deploy\Data\*.*
 - path: deploy\Data\Shaders\*.*
 - path: deploy\Data\Textures\*.*

#deploy:
#- provider: GitHub
#  tag: vrtestapp-$(appveyor_build_version)-$(platform)
#  release: vrtestapp-$(appveyor_build_version)-$(platform)
#  description: VR Test App release
#  auth_token:
#    secure: a1D+fCbSKHqq30FF/sF1hGvs+WHLMrZ2JFKkYS4SdjOOdyve83el5ejZrv5cSYDh
#  draft: true
#  prerelease: false
