version: build.{build}

os: Visual Studio 2013

clone_folder: c:\!BuildOSVR\VRTestApp

platform:
 - Win32
 - x64

configuration:
 - Debug
 - Release

#matrix:
# allow_failured:
#  - platform: x64
#    configuration: Debug

install:
 - cmake --version
 - git submodule update --init --recursive -q

before_build:
 - pushd .
 - echo "Listing OpenVR libdir..."
 - cd C:\!BuildOSVR\VRTestApp\libs
 - dir /s /b
 - echo "Starting build..."
 - popd

build:
 project c:\!BuildOSVR\VRTestApp\VRTestApp.sln

#test_script:
# - cd c:\!BuildOSVR\VRTestApp
