version: v1.0.{build}

branches:
 only:
 - master

skip_tags: true

os: Visual Studio 2013

clone_folder: c:\!BuildOSVR\VRTestApp

platform:
 - Win32
 - x64

configuration:
# - Debug
 - Release

matrix:
 allow_failures:
  - platform: x64
    configuration: Release

install:
 - cmake --version
 - git submodule update --init --recursive -q

before_build:
 - echo "Starting build..."

#build:
#  project: VRTestApp.sln
#  verbosity: normal
# verbosity: quiet|minimal|normal|detailed

build_script:
 - .\scripts\build.ps1

after_build:
 - cmd: mkdir deploy
 - cmd: xcopy .\Working\SDL2.dll .\deploy\
 - cmd: xcopy .\Working\openvr_api.dll .\deploy\
# - cmd: xcopy .\Working\d3dcompiler_47.dll .\deploy\
 - cmd: xcopy .\Working\Data .\deploy\Data /i /e
 - cmd: xcopy .\%CONFIGURATION%\VRTestApp.exe .\deploy\
 - cmd: 7z a vrtestapp-binary-%PLATFORM%-%APPVEYOR_BUILD_VERSION%.zip %APPVEYOR_BUILD_FOLDER%\deploy\

artifacts:
 - path: vrtestapp-binary-%PLATFORM%-%APPVEYOR_BUILD_VERSION%.zip

deploy:
- provider: GitHub
  tag: vrtestapp-$(appveyor_build_version)-$(platform)
  release: VRTestApp-$(appveyor_build_version)-$(platform)
  description: VR Test App release $(appveyor_build_version) - $(platform)
  auth_token:
    secure: a1D+fCbSKHqq30FF/sF1hGvs+WHLMrZ2JFKkYS4SdjOOdyve83el5ejZrv5cSYDh
  artifact: vrtestapp-binary-%PLATFORM%-%APPVEYOR_BUILD_VERSION%.zip
  draft: false
  prerelease: false
